# .github/workflows/docker-image.yml

name: Build and Push Docker Image

# 1. 언제 실행할 것인가?
# main 브랜치에 push 이벤트가 발생했을 때 실행
on:
  push:
    branches: [ "main" ]

# 2. 어떤 작업을 할 것인가?
jobs:
  build:
    # 3. 어떤 환경에서 실행할 것인가?
    # 최신 버전의 우분투 가상 머신에서 실행
    runs-on: ubuntu-latest

    # 4. 어떤 순서로 실행할 것인가?
    steps:
      # 내 GitHub 저장소의 코드를 가상 머신으로 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # Jetson(arm64)용 이미지를 빌드하기 위한 QEMU 설정
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Docker Buildx 설정 (멀티 플랫폼 빌드를 위함)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub에 로그인하기
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 Docker Hub에 푸시하기
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64  # Jetson 아키텍처 지정
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-jetson-app:latest # 이미지 이름:태그